# Generated by Django 6.0.3 on 2026-03-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_id_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='progress',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='submitted', max_length=20),
        ),
    ]
