# Generated by Django 6.0.3 on 2026-03-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_comment_is_hidden_comment_parent_report_assigned_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedReportFilter',
        ),
    ]
