# Generated by Django 6.0.3 on 2026-03-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_delete_savedreportfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
