# Generated by Django 6.0.2 on 2026-03-12 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_latitude_report_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['report', 'parent', 'is_hidden', 'created_at'], name='reports_com_report__cce3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='reports_not_recipie_9978f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['report', 'created_at'], name='reports_not_report__239199_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', 'created_at'], name='reports_rep_user_id_9178ae_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_hidden', 'created_at'], name='reports_rep_is_hidd_98c634_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['progress', 'created_at'], name='reports_rep_progres_df8fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category', 'created_at'], name='reports_rep_categor_f39dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='reportstatushistory',
            index=models.Index(fields=['report', 'new_status', 'created_at'], name='reports_rep_report__a4b881_idx'),
        ),
    ]
