# Generated by Django 6.0.2 on 2026-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_comment_reports_com_report__cce3b1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('angry', 'Angry'), ('dislike', 'Dislike')], default='like', max_length=20),
        ),
        migrations.AddField(
            model_name='reportreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('angry', 'Angry'), ('dislike', 'Dislike')], default='like', max_length=20),
        ),
    ]
